---
#Service Spec for Kibana front end for ES
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elk-logging
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
  selector:
    app: kibana
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elk-logging
  labels:
    app: kibana
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.8.0
        #resources:
        #  requests:
        #    cpu: "100m"
        #    memory: "512M"
        #  limits:
        #    cpu: "100m"
        #    memory: "512M"
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch.elk-logging:9200
        ports:
        - containerPort: 5601
# New server address in elk-logging namespace