# Shrink default JVM heap.
logstashJavaOpts: "-Xmx128m -Xms128m"

resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi

service: {}
  annotations: {}
  type: LoadBalancer
  ports:
    - name: pem
      port: 5514
      protocol: TCP
      targetPort: 5514
    - name: dns
      port: 5515
      protocol: TCP
      targetPort: 5515
    - name: afm
      port: 5516
      protocol: TCP
      targetPort: 5516